### ISSUE TITLE
tx fees to mining rewards

### ISSUE THREAD

**Issue by raskul** [XDagger/xdag#134]
please add 0.01 tx fees to transactions, to be given to mining rewards. this will stabalise the network hugely.

**Comment by leruy** [comment]
if add tx fees, how to generate new address?

**Comment by jonano614** [comment]
Transaction fees are not planned in the close future.

**Comment by trueserve** [comment]
Actually, transaction fees should be used as one mitigation for network spam, and the code is already present. But there are some blockers.

1. Right now the pools send to all miners for each found block. This results in a large amount of transactions. Thus, the pool logic should be revised to not pay out on every block, but instead after the miner passes a threshold payment value.
2. Low TX fees alone won't stop deliberate attacks on the network. Because it is so easy to forge a block, even with a low TX fee, attacks can still happen. This is not a reason to _not_ implement a fee, but something worth considering.
3. The whitepaper talks about fees propagating through blocks, or being additive to them. This is an incentive for mined blocks, but what does it do for transaction blocks that include links to other blocks?
4. This all still needs to be tested.

Once the pool is updated, this should be revisited.
